apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: php-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-backend
  template:
    metadata:
      labels:
        app: php-backend
    spec:
      containers:
      - name: php-backend
        image: milamber/php-backend:latest
        ports:
        - containerPort: 8080
